[package]
name = "task2"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.15.2"
solana-client = "1.15.2"
solana-program = "1.15.2"
bs58 = "0.5.1"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }
borsh = "0.9.1"